name: Deploy Vite App to VPS

on:
  push:
    branches:
      - master  # Adjust to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci  # 'npm ci' for clean installs

    - name: Build Vite project
      run: npm run build

    - name: List dist contents
      run: ls -R dist

    - name: Create deployment test file
      run: echo "Vite deployment test $(date)" > dist/test.txt

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 4020
        source: "dist/*"
        target: "/var/www/jdwd40.com/html/ms"  # Adjust if your app's directory is different
        strip_components: 1

    - name: Verify deployment and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 4020
        script: |
          echo "Contents of /var/www/jdwd40.com/html/ms:"
          ls -la /var/www/jdwd40.com/html/ms
          echo "Content of test.txt:"
          cat /var/www/jdwd40.com/html/ms/test.txt
          echo "Restarting Nginx..."
          sudo systemctl restart nginx
          echo "Nginx restarted."
