name: Deploy Vite App

on:
  push:
    branches:
      - main  # or whichever branch you use for deployments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the version you need

    - name: Install dependencies
      run: npm install

    - name: Build Vite app
      run: npm run build

    - name: Deploy to VPS
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        HOST: ${{ secrets.VPS_HOST }}
        USER: ${{ secrets.VPS_USER }}
        PORT: ${{ secrets.VPS_PORT }}
        TARGET_DIR: /var/www/jdwd40.com/html/ms

      run: |
        # Configure known hosts
        mkdir -p ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        # Package and transfer files
        tar -czf dist.tar.gz -C dist .
        scp -P $PORT dist.tar.gz $USER@$HOST:$TARGET_DIR
        ssh -p $PORT $USER@$HOST "tar -xzf $TARGET_DIR/dist.tar.gz -C $TARGET_DIR && rm $TARGET_DIR/dist.tar.gz"
